[2025-08-06 04:43:00,361] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 05:53:19,044] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 06:15:29,159] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 06:47:21,195] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 07:06:41,957] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 07:34:41,403] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 09:14:29,065] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 09:58:56,608] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 09:58:58,763] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 12:17:30,388] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 12:18:02,571] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 12:19:16,124] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 13:08:02,535] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
[2025-08-06 13:11:52,467] ERROR in app: Exception on /notices [GET]
Traceback (most recent call last):
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/app.py", line 51, in notices
    return render_template('public/notices.html', notices=all_notices)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/layout.html", line 131, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/prachinbd.com/templates/public/notices.html", line 74, in block 'content'
    <a href="{{ url_for('index') }}" class="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-300">
    ^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/prachinbd/virtualenv/prachinbd.com/3.13/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'notices' instead?
